### ISSUE TITLE
erlfsmon failed to start

### ISSUE THREAD

**Issue by 5HT** [proger/erlfsmon#2]
Failed to watch /home/maxim/synrc/countach; upper limit on inotify watches reached!

**Comment by proger** [comment]
you may want to twist `sysctl fs.inotify.max_user_watches` first

**Comment by 5HT** [comment]
Thanks, would be good to mention in README.

**Comment by proger** [comment]
Apart from that it's worth checking that `inotifywait` doesn't watch any extra non-build-related files too.

**Comment by 5HT** [comment]
How to do that ?

**Comment by proger** [comment]
`inotifywait` simply recursively watches everything in your project dir. How many files are there?

**Comment by 5HT** [comment]
Not so much. As usual. I guess the cause of that error is cumulative. It doesn't depends on files, but on number of reloads. erlfsmon was running for couple days. After sudo restart everything is ok.
