### ISSUE TITLE
inotifywait does not absname() relative to provided Cwd

### ISSUE THREAD

**Issue by jjl** [proger/erlfsmon#4]
https://github.com/proger/erlfsmon/blob/master/src/inotifywait.erl#L8

You can switch to `absname/2` to provide the Cwd

**Comment by proger** [comment]
Could you provide an example where this is a problem?

**Comment by proger** [comment]
I've dropped support for inotifywait in favor of [fswatch](https://github.com/emcrisostomo/fswatch).
